### ISSUE TITLE
AUR

### ISSUE THREAD

**Issue by zzzardoz** [zynexiz/RenameMyTVSeries#1]
<a href="https://imgflip.com/i/36uh86"><img src="https://i.imgflip.com/36uh86.jpg" title="made at imgflip.com"/></a>

**Comment by zynexiz** [comment]
Ok, I get the point 🙂 I'll see what I can do about it.

**Comment by zynexiz** [comment]
Added to AUR.

https://aur.archlinux.org/packages/renamemytvseries-bin/
